// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjsx2FBQg9R7naOSH_4H0Qi6600e9TRXk',
    appId: '1:870368255263:web:66cc9128d7b4a75a86242a',
    messagingSenderId: '870368255263',
    projectId: 'tea-time-unilink',
    authDomain: 'tea-time-unilink.firebaseapp.com',
    storageBucket: 'tea-time-unilink.appspot.com',
    measurementId: 'G-V5ME2SVZ45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgfv276xgZmJLAUwD_PX-06n5hdiz_LmA',
    appId: '1:870368255263:android:af3cd0c4e8e828f786242a',
    messagingSenderId: '870368255263',
    projectId: 'tea-time-unilink',
    storageBucket: 'tea-time-unilink.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCouuuRNtSQkYC9IO_L008shFLO6L9LjDc',
    appId: '1:870368255263:ios:09494716b1bf200f86242a',
    messagingSenderId: '870368255263',
    projectId: 'tea-time-unilink',
    storageBucket: 'tea-time-unilink.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCouuuRNtSQkYC9IO_L008shFLO6L9LjDc',
    appId: '1:870368255263:ios:09494716b1bf200f86242a',
    messagingSenderId: '870368255263',
    projectId: 'tea-time-unilink',
    storageBucket: 'tea-time-unilink.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjsx2FBQg9R7naOSH_4H0Qi6600e9TRXk',
    appId: '1:870368255263:web:137045740afa4cac86242a',
    messagingSenderId: '870368255263',
    projectId: 'tea-time-unilink',
    authDomain: 'tea-time-unilink.firebaseapp.com',
    storageBucket: 'tea-time-unilink.appspot.com',
    measurementId: 'G-EKW8FCYVQ9',
  );

}